/*ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
  บ  Dateiname:        ctools.h                       Datum: 10.11.88      บ
  วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤถ
  บ                                                                        บ
  บ  Mit dieser Datei k”nnen Sie mit einer Anweisung alle Header-          บ
  บ  Dateien der C-Tools in Ihren Source-Code einbinden.                   บ
  บ                                                                        บ
  บ  Die Reihenfolge darf nicht verndert werden.                          บ
  บ                                                                        บ
  วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤถ
  บ            Autoren: Rainer G. Haselier und Klaus Fahnenstich           บ
  บ     (c) copyright 1988 Markt & Technik Verlag AG, Haar bei Mnchen     บ
  ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ*/

#ifndef CT_TYPEN_HEADER
#include <cttypen.h>
#endif

#ifndef CT_DIALOG_HEADER
#include <ctdlg.h>
#endif

#ifndef CT_VIDEO_HEADER
#include <ctvio.h>
#endif

#ifndef CT_MENU_HEADER
#include <ctmnu.h>
#endif

#ifndef CT_UTIL_HEADER
#include <ctutl.h>
#endif

#ifndef CT_WINDOW_HEADER
#include <ctwin.h>
#endif

#ifndef CT_INTERN_HEADER
#include <ctintern.h>
#endif

#ifndef CT_MAUS_HEADER
#include <ctmsm.h>
#endif

/*
#ifndef CT_INTERN_HEADER
#include <ctintern.h>
#endif
    */
