//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IniConfig.Console.lib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IniConfig.Console.lib.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new entry in a section.
        /// </summary>
        public static string CreateEntryCommand_Description {
            get {
                return ResourceManager.GetString("CreateEntryCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new section.
        /// </summary>
        public static string CreateSectionCommand_Description {
            get {
                return ResourceManager.GetString("CreateSectionCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of the file path not found.
        /// </summary>
        public static string Error_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Error_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section not found.
        /// </summary>
        public static string Error_SectionNotFound {
            get {
                return ResourceManager.GetString("Error_SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List entries of a section.
        /// </summary>
        public static string ListEntriesCommand_Description {
            get {
                return ResourceManager.GetString("ListEntriesCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found entries in section {0}:.
        /// </summary>
        public static string ListEntriesCommand_Header {
            get {
                return ResourceManager.GetString("ListEntriesCommand_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List sections of configuration file.
        /// </summary>
        public static string ListSectionsCommand_Description {
            get {
                return ResourceManager.GetString("ListSectionsCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found sections:.
        /// </summary>
        public static string ListSectionsCommand_Header {
            get {
                return ResourceManager.GetString("ListSectionsCommand_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load configuration file.
        /// </summary>
        public static string LoadCommand_Description {
            get {
                return ResourceManager.GetString("LoadCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove entry.
        /// </summary>
        public static string RemoveEntryCommand_Description {
            get {
                return ResourceManager.GetString("RemoveEntryCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove section.
        /// </summary>
        public static string RemoveSectionCommand_Description {
            get {
                return ResourceManager.GetString("RemoveSectionCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration file.
        /// </summary>
        public static string SaveCommand_Description {
            get {
                return ResourceManager.GetString("SaveCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attribute given.
        /// </summary>
        public static string Warning_NoAttributeGiven {
            get {
                return ResourceManager.GetString("Warning_NoAttributeGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No config file loaded.
        /// </summary>
        public static string Warning_NoFileLoaded {
            get {
                return ResourceManager.GetString("Warning_NoFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file name given.
        /// </summary>
        public static string Warning_NoFilenameGiven {
            get {
                return ResourceManager.GetString("Warning_NoFilenameGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No section name given.
        /// </summary>
        public static string Warning_NoSectionNameGiven {
            get {
                return ResourceManager.GetString("Warning_NoSectionNameGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sections found.
        /// </summary>
        public static string Warning_NoSectionsFound {
            get {
                return ResourceManager.GetString("Warning_NoSectionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value given.
        /// </summary>
        public static string Warning_NoValueGiven {
            get {
                return ResourceManager.GetString("Warning_NoValueGiven", resourceCulture);
            }
        }
    }
}
