// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Slesa Solutions")]
[assembly: AssemblyCopyrightAttribute("Copyright Slesa © 2013")]
[assembly: AssemblyTrademarkAttribute("Slesa Solutions")]
[assembly: AssemblyVersionAttribute("0.9.0.0")]
[assembly: AssemblyFileVersionAttribute("0.9.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.9.0.0";
    }
}
