// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IniConfig - Command line interface to edit files, application")]
[assembly: GuidAttribute("4639d91e-a60a-4eb1-8e36-425a69cf4934")]
[assembly: AssemblyProductAttribute("IniConfig Configuration Files")]
[assembly: AssemblyCompanyAttribute("Slesa Solutions")]
[assembly: AssemblyCopyrightAttribute("Copyright Slesa © 2013")]
[assembly: AssemblyTrademarkAttribute("Slesa Solutions")]
[assembly: AssemblyVersionAttribute("0.9.0.0")]
[assembly: AssemblyFileVersionAttribute("0.9.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.9.0.0";
    }
}
