//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IniConfig.Editor.lib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IniConfig.Editor.lib.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load existing configuration file.
        /// </summary>
        public static string MenuBarView_LoadCommandTooltip {
            get {
                return ResourceManager.GetString("MenuBarView_LoadCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new configuration file.
        /// </summary>
        public static string MenuBarView_NewCommandTooltip {
            get {
                return ResourceManager.GetString("MenuBarView_NewCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit program.
        /// </summary>
        public static string MenuBarView_QuitCommandTooltip {
            get {
                return ResourceManager.GetString("MenuBarView_QuitCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load recently used configuration file.
        /// </summary>
        public static string MenuBarView_RecentFilesTooltip {
            get {
                return ResourceManager.GetString("MenuBarView_RecentFilesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current configuration to a different file.
        /// </summary>
        public static string MenuBarView_SaveAsCommandTooltip {
            get {
                return ResourceManager.GetString("MenuBarView_SaveAsCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to current configuration file.
        /// </summary>
        public static string MenuBarView_SaveCommandTooltip {
            get {
                return ResourceManager.GetString("MenuBarView_SaveCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string MenuBarViewModel_AllFiles {
            get {
                return ResourceManager.GetString("MenuBarViewModel_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration files.
        /// </summary>
        public static string MenuBarViewModel_ConfigurationFiles {
            get {
                return ResourceManager.GetString("MenuBarViewModel_ConfigurationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load {0}.
        /// </summary>
        public static string MenuBarViewModel_CouldNotLoadFile {
            get {
                return ResourceManager.GetString("MenuBarViewModel_CouldNotLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} successfully loaded.
        /// </summary>
        public static string MenuBarViewModel_FileLoaded {
            get {
                return ResourceManager.GetString("MenuBarViewModel_FileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuation file as....
        /// </summary>
        public static string MenuBarViewModel_SaveConfigurationFileAs {
            get {
                return ResourceManager.GetString("MenuBarViewModel_SaveConfigurationFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a configuration file....
        /// </summary>
        public static string MenuBarViewModel_SelectConfigurationFile {
            get {
                return ResourceManager.GetString("MenuBarViewModel_SelectConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Msg_Ready {
            get {
                return ResourceManager.GetString("Msg_Ready", resourceCulture);
            }
        }
    }
}
